version: '3.3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_servidor
    restart: always
    ports:
      - "5100:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tienda
      MYSQL_USER: tienda_user
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
